file.remove("NAMESPACE") |> suppressWarnings()
usethis::use_proprietary_license(copyright_holder = "Alejandro Verri Kozlowski")
devtools::check(document = TRUE)
remove.packages("gmsp") |> suppressWarnings()
devtools::install()
# remotes::install_github("averriK/gmsp")
